"""Add image_file, about_me, last_seen to User

Revision ID: 241730aaa2ff
Revises: 9bd1d9d4fbec
Create Date: 2025-11-30 10:57:37.594807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241730aaa2ff'
down_revision = '9bd1d9d4fbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=False, server_default='default.png'))
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))   

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
